Adds better error for missing inputs
Trying to make it simpler for someone to figure out what
to fix.

E.g. if they do something like:

```python
app.run(halt_after=["response"])
```
but input is required, they'll get:
```
ValueError: Action prompt is missing required inputs: {'prompt'}. Has inputs: {}.
Please double check the values passed to the keyword argument `inputs` to however you're running the burr application.
e.g.
   app.run( # or app.step, app.iterate, app.astep, etc.
       halt_..., # your halt logic
       inputs={'prompt': 'FILL ME IN'}  # <-- this is what you need to adjust
   )
```